export const DailyForecast = () => {
    return (
        <article style={{display: "flex"}}>
            <div>
                <p>Tue</p>
                <p>icons</p>
                <div>
                    <p>min</p>
                     <p>max</p>
                </div>
            </div>
            <div>
                <p>Tue</p>
                <p>icons</p>
                <div>
                    <p>min</p>
                     <p>max</p>
                </div>
            </div>
            <div>
                <p>Tue</p>
                <p>icons</p>
                <div>
                    <p>min</p>
                     <p>max</p>
                </div>
            </div>
            <div>
                <p>Tue</p>
                <p>icons</p>
                <div>
                    <p>min</p>
                     <p>max</p>
                </div>
            </div>
            <div>
                <p>Tue</p>
                <p>icons</p>
                <div>
                    <p>min</p>
                     <p>max</p>
                </div>
            </div>
            <div>
                <p>Tue</p>
                <p>icons</p>
                <div>
                    <p>min</p>
                     <p>max</p>
                </div>
            </div>
            <div>
                <p>Tue</p>
                <p>icons</p>
                <div>
                    <p>min</p>
                     <p>max</p>
                </div>
            </div>
        </article>
    )
}